require "yaml"
vagrant_root = File.dirname(File.expand_path(__FILE__))
settings = YAML.load_file "#{vagrant_root}/settings.yaml"

IP_SECTIONS = settings["network"]["jenkins_ip"].match(/^([0-9.]+\.)([^.]+)$/)

IP_NW = IP_SECTIONS.captures[0]

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      echo "$IP_NW$((IP_START)) jenkins" >> /etc/hosts
  SHELL

  if `uname -m`.strip == "aarch64"
    config.vm.box = settings["software"]["box"] + "-arm64"
  else
    config.vm.box = settings["software"]["box"]
  end
  config.vm.box_check_update = true
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: settings["network"]["jenkins_ip"]
    if settings["shared_folders"]
      settings["shared_folders"].each do |shared_folder|
        jenkins.vm.synced_folder shared_folder["host_path"], shared_folder["vm_path"]
      end
    end
    jenkins.vm.provider "virtualbox" do |vb|
        vb.cpus = settings["nodes"]["control"]["cpu"]
        vb.memory = settings["nodes"]["control"]["memory"]
        if settings["server_name"] and settings["server_name"] != ""
          vb.customize ["modifyvm", :id, "--groups", ("/" + settings["server_name"])]
        end
    end
    jenkins.vm.provision "shell",
      path: "scripts/install.sh"
  end
end 

